### ISSUE TITLE
Invisible fonts on microsoft.com

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#45]
https://products.office.com/EN-US/whats-new-office?Wt.mc_id=oan_EN-US_mscom_prog_office2016launchwhatsnew#

```css
@font-face {
	font-family:'wf_segoe-ui_light';
	src:url("//i.s-microsoft.com/fonts/segoe-ui/west-european/light/latest.eot");
	src:local("Segoe UI Light"),local("Segoe WP Light"),url("//i.s-microsoft.com/fonts/segoe-ui/west-european/light/latest.eot?#iefix") format("embedded-opentype"),url("//i.s-microsoft.com/fonts/segoe-ui/west-european/light/latest.woff") format("woff"),url("//i.s-microsoft.com/fonts/segoe-ui/west-european/light/latest.ttf") format("truetype");
	font-weight:normal;
	font-style:normal;
	-webkit-font-smoothing:antialiased
}
```
