### ISSUE TITLE
Multiple issues with https://ionicframework.com/docs/

### ISSUE THREAD

**Issue by trollixx** [annulen/webkit#707]
1. In QtWK this web page is rendered with fonts different from other browsers, and a series of the error messages like the following gets printed:

```
QWindowsFontDatabase::fontEngine: Can't change family name of font
```

2. An image is improperly resized. See the screenshot (Firefox on the left, QtWK on the right):

![qtwk-image-bug](https://user-images.githubusercontent.com/714940/34501632-723d3ac4-f018-11e7-902b-d1b932ab2f87.png)

**Comment by annulen** [comment]
For completeness, could you show in screenshot where are different fonts?

AFAIU stylesheet of top menu uses this
```css
@font-face {
  font-family: "Avenir Next";
  font-weight: 600;
  src: local("Avenir Next Demi Bold"), url("/fonts/avenir-next/demi.woff2") format("woff2"), url("/fonts/avenir-next/demi.woff") format("woff"), url("/fonts/avenir-next/demi.ttf") format("ttf"), url("/fonts/avenir-next/demi.eot?#iefix") format("eot");
  unicode-range: U+0-5FF;
}
```
It can be that web font failed to load (you can check in Inspector's Network tab), or it wasn't handled correctly by QWindowsFontEngine
